# Generated by Django 2.0.2 on 2018-02-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentrymodel',
            name='access_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
