# Generated by Django 2.0.2 on 2018-02-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ListofPharmaceuticalProducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicallist',
            name='comments',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='medicallist',
            name='composition',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='medicallist',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='medicallist',
            name='reimbursible',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicallist',
            name='usage',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
