# Generated by Django 2.0.2 on 2018-02-23 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ListofPharmaceuticalProducts', '0002_auto_20180220_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicallist',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
